version: '3.7'

services:
  polygons_main:
    container_name: polygons_main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: yarn run start:dev
    networks:
      - webnet

  polygons_mongo:
    image: mongo
    container_name: polygons_mongo
    environment:
      MONGO_INITDB_DATABASE: polygons
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tui2020
    ports:
      - '37017:27017'
    volumes:
      - ./docker/volumes/mongodb:/data/db
    networks:
      - mongo_network

  polygons_mongo_client:
    image: mongoclient/mongoclient:latest
    container_name: polygons_mongo_client
    hostname: mongoclient
    depends_on:
      - polygons_mongo
    ports:
      - 3300:3000
    networks:
      - mongo_network

networks:
  webnet:
  mongo_network:
    driver: bridge
    ipam:
      driver: default
